### ISSUE TITLE
"Only RGBS supported"

### ISSUE THREAD

**Issue by TrocelengStudios** [HolyWu/vs-dpir#2]
I tried to input video and the script gave me an error saying "Only RGBS supported". What even is RGBS video?

I tested converting to RGB64, RGB32 and RGB24 using Virtualdub, but all of them resulted in the same "Only RGBS supported" message. What am I supposed to do?

**Comment by Ichunjo** [comment]
RGBS is 32bit float. On Vapoursynth you can easily convert a clip using the built resizers like that:
```py
rgb = core.resize.Bicubic(clip, format=vs.RGBS)
```
