### ISSUE TITLE
missing onnxruntime on setup.cfg(?)

### ISSUE THREAD

**Issue by sl1pkn07** [HolyWu/vs-dpir#23]
Hi

i'm not python coder, but, should be added onnxruntime on the install_requires field into setup.cfg file?

greetings

**Comment by HolyWu** [comment]
I didn't add onnxruntime to the `install_requires` field because the python package name is different depending on the hardware acceleration the user chooses. It could be `onnxruntime`, `onnxruntime-gpu`, `onnxruntime-directml`, or `onnxruntime-powerpc64le`, etc.
