### ISSUE TITLE
Failed to evaluate the script

### ISSUE THREAD

**Issue by gxfasd** [HolyWu/vs-dpir#30]
my script:

> from vsdpir import dpir
core = vs.core
ret= core.lsmas.LWLibavSource(r'C:\Users\Administrator\Desktop\12.mp4')
ret = core.resize.Bicubic(ret, format=vs.RGBS, matrix_in_s="470bg", dither_type="error_diffusion")
ret = dpir(ret)
ret = core.resize.Bicubic(ret, format=vs.YUV420P16, matrix_s="709", range_s="full")
ret.set_output()> 

The script ran incorrectly：

> Failed to evaluate the script:
Python exception: cannot import name 'dpir' from 'vsdpir' (D:\video\VapourSynth64Portablevb\VapourSynth64\Lib\site-packages\vsdpir\__init__.py)
Traceback (most recent call last):
File "src\cython\vapoursynth.pyx", line 2866, in vapoursynth._vpy_evaluate
File "src\cython\vapoursynth.pyx", line 2867, in vapoursynth._vpy_evaluate
File "D:/video/VapourSynth64Portablevb/dpir.vpy", line 29, in 
from vsdpir import dpir
ImportError: cannot import name 'dpir' from 'vsdpir' (D:\video\VapourSynth64Portablevb\VapourSynth64\Lib\site-packages\vsdpir\__init__.py)> 

vs-famser is ok.

**Comment by HolyWu** [comment]
I cannot help you as you are using an unofficial installation since there is no `vsdpir_init.py` in this package.

**Comment by gxfasd** [comment]
I have solved this problem. Can using trt improve the image quality? @ @HolyWu

**Comment by gxfasd** [comment]
Image Super-Resolution
https://github.com/XPixelGroup/HAT
Can you import into vs?

**Comment by HolyWu** [comment]
HAT is too VRAM demanding and unusable in FP16 mode. Just use SwinIR.
