### ISSUE TITLE
TensorRT whl for Vapoursynth R62, Python 3.11  ?

### ISSUE THREAD

**Issue by Selur** [HolyWu/vs-dpir#32]
I'm trying to get vs-dpir working with the new Vapoursynth R62 which does not support Python 3.10 anymore.
Can you build and share a new tensoRTxxx.whl file which works with Python 3.11?

**Comment by HolyWu** [comment]
No, I didn't build it. The Python wheel file was provided in the zip package at https://developer.nvidia.com/tensorrt. The latest 8.6 EA still doesn't support Python 3.11.

**Comment by Selur** [comment]
Ah okay, the file comes from TensorRT-8.6.0.12.Windows10.x86_64.cuda-11.8.zip\TensorRT-8.6.0.12\python :)
So, conclusion for now is to wait for a new tensorrt release before one can use Vapoursynth R62 with Python 3.11 and vs-dpir&co.
Do you have any experience how long it usually last till a new Python version is supported my NVIDIAs TensorRT?

**Comment by HolyWu** [comment]
No idea. Python 3.9 was supported in [v8.0.1](https://github.com/NVIDIA/TensorRT/releases/tag/8.0.1). Python 3.10 was supported in [v8.4.3](https://github.com/NVIDIA/TensorRT/releases/tag/8.4.3).

**Comment by Selur** [comment]
Okay, so there is hope,.. :)
Thanks.

**Comment by Selur** [comment]
TensorRT-8.6.1.6.Windows10.x86_64.cuda-11.8.zip has a tensorrt-8.6.1-cp311-none-win_amd64.whl :)
