### ISSUE TITLE
Question regarding dependencies and other projects

### ISSUE THREAD

**Issue by Selur** [HolyWu/vs-dpir#42]
Motivated that I got vs-dpir working with your help, I wanted to add your other projects, but can into a few problems.
(Sorry, this is a bit longer, but I wanted to be sure you know what I did so you might be able to see what I missed or did wrong.)

What I did was
* create 'Vapoursynth'-folder
* downloaded 'Windows embeddable package (64-bit)' from https://www.python.org/downloads/release/python-3123/
* extracted it into the 'Vapoursynth'-folder
* downloaded 'VapourSynth64-Portable-R68' from https://github.com/vapoursynth/vapoursynth/releases
* extracted it into the 'Vapoursynth'-folder
* download get-pip.py from https://bootstrap.pypa.io/get-pip.py into the 'Vapoursynth'-folder
* ran `python get-pip.py`
* adjusted `python312._pth` by adding:
  ```
  Scripts
  Lib\site-packages
  ```
* called `python -m pip install wheel/VapourSynth-68-cp312-cp312-win_amd64.whl`
* downloaded https://github.com/HolyWu/vs-dpir/releases/download/v4.0.0/torch_tensorrt-2.4.0.dev0+8915f846d-cp312-cp312-win_amd64.whl
* called:
** `python -m pip install wheel`
** `python -m pip install torch_tensorrt-2.4.0.dev0+8915f846d-cp312-cp312-win_amd64.whl`
** `python -m pip install --pre torch-tensorrt --index-url https://download.pytorch.org/whl/nightly/cu121`
* installed vs-dpir, by calling
** `python -m pip install git+https://github.com/Jaded-Encoding-Thaumaturgy/vs-tools.git`
** `pip install -U vsdpir`
** `python -m vsdpir`
* installed vsgan by calling:
** `python -m pip install -U VSGAN`
** `python -m pip install -U vsgmfss-fortuna`
* installed SwinIR by calling:
** `python -m pip install -U vsswinir
** `python -m vsswinir`
* installed HINet by calling:
** `python -m pip install --upgrade vshinet`
** `python -m vshinet`
* installed AnimeSR by calling:
** `python -m pip install -U vsanimesr`
* installed SCUNet by calling:
** `python -m pip install -U vsscunet`
** `python -m vsscunet`
* installed CodeFormer by calling:
** `python -m pip install -U vscodeformer`
** `python -m vscodeformer`
* installed GRLIR, by calling:
** `python -m pip install antlr4-python3-runtime`
** `python -m pip install -U vsgrlir`
** `python -m vsgrlir`

So far so good.

Next thing I tried was, installing vs-realesrgan, by calling:
* `python -m pip install -U vsrealesrgan`
* `python -m vsrealesrgan`
this ended with:
```
F:\Vapoursynth>python -m vsrealesrgan
Traceback (most recent call last):
  File "<frozen runpy>", line 189, in _run_module_as_main
  File "<frozen runpy>", line 148, in _get_module_details
  File "<frozen runpy>", line 112, in _get_module_details
  File "F:\Vapoursynth\Lib\site-packages\vsrealesrgan\__init__.py", line 14, in <module>
    from torch_tensorrt.fx import LowerSetting
  File "F:\Vapoursynth\Lib\site-packages\torch_tensorrt\__init__.py", line 114, in <module>
    _register_with_torch()
  File "F:\Vapoursynth\Lib\site-packages\torch_tensorrt\__init__.py", line 107, in _register_with_torch
    torch.ops.load_library(linked_file_full_path)
  File "F:\Vapoursynth\Lib\site-packages\torch\_ops.py", line 1032, in load_library
    ctypes.CDLL(path)
  File "ctypes\__init__.py", line 379, in __init__
FileNotFoundError: Could not find module 'F:\Vapoursynth\Lib\site-packages\torch_tensorrt\lib\torchtrt.dll' (or one of its dependencies). Try using the full path with constructor syntax.
```
I then checked `F:\Vapoursynth\Lib\site-packages\torch_tensorrt\lib\torchtrt.dll` and it did exist.
So, one of it's dependencies must be missing. :(
using https://github.com/lucasg/Dependencies an throwding `torchtrt.dll` it showed the following dependencies:
* nvinfer_plugins10.dll (present at `F:\Vapoursynth\Lib\site-packages\tensorrt_libs\nvinfer_plugin_10.dll` and `F:\Vapoursynth\torch_dependencies\bin\nvinfer_plugin_10.dll`)
* cuart64_12.dll (not present)
* nvinfer_10.dll (present at `F:\Vapoursynth\torch_dependencies\bin\nvinfer_10.dll` and `F:\Vapoursynth\torch_dependencies\bin\nvinfer_plugin_10.dl`)
* torch_cpu.dll (present at `F:\Vapoursynth\Lib\site-packages\torch\lib\torch_cpu.dll`)
* cu10_cuda.dll (not present)
* c10.dll (present at F:\Vapoursynth\Lib\site-packages\torch\lib\c10.dll)

I know, that cuart64_12.dll comes in https://developer.download.nvidia.com/compute/cuda/12.4.1/local_installers/cuda_12.4.1_551.78_windows.exe

I hoped using:
`python pip install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cu121`
could help, but that ended with:
```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
torch-tensorrt 2.4.0.dev0+8915f846d requires torch<2.4.0,>=2.3.0, but you have torch 2.4.0.dev20240513+cu121 which is incompatible.
```

So that did not work, next I tried vsrife:
* `python -m pip install --upgrade vsrife`
* `python -m vsrife`
ended with:
```
Traceback (most recent call last):
  File "<frozen runpy>", line 189, in _run_module_as_main
  File "<frozen runpy>", line 148, in _get_module_details
  File "<frozen runpy>", line 112, in _get_module_details
  File "F:\Vapoursynth\Lib\site-packages\vsrife\__init__.py", line 14, in <module>
    from torch_tensorrt.fx import LowerSetting
  File "F:\Vapoursynth\Lib\site-packages\torch_tensorrt\__init__.py", line 114, in <module>
    _register_with_torch()
  File "F:\Vapoursynth\Lib\site-packages\torch_tensorrt\__init__.py", line 107, in _register_with_torch
    torch.ops.load_library(linked_file_full_path)
  File "F:\Vapoursynth\Lib\site-packages\torch\_ops.py", line 1242, in load_library
    ctypes.CDLL(path)
  File "ctypes\__init__.py", line 379, in __init__
OSError: [WinError 127] Die angegebene Prozedur wurde nicht gefunden
```

Next I tried installing vsfemasr:
* `python -m pip install -U vsfemasr` 
* `python -m vsfemasr`
endend with:
```
Traceback (most recent call last):
  File "<frozen runpy>", line 189, in _run_module_as_main
  File "<frozen runpy>", line 148, in _get_module_details
  File "<frozen runpy>", line 112, in _get_module_details
  File "F:\Vapoursynth\Lib\site-packages\vsfemasr\__init__.py", line 13, in <module>
    from torch_tensorrt.fx import LowerSetting
  File "F:\Vapoursynth\Lib\site-packages\torch_tensorrt\__init__.py", line 114, in <module>
    _register_with_torch()
  File "F:\Vapoursynth\Lib\site-packages\torch_tensorrt\__init__.py", line 107, in _register_with_torch
    torch.ops.load_library(linked_file_full_path)
  File "F:\Vapoursynth\Lib\site-packages\torch\_ops.py", line 1242, in load_library
    ctypes.CDLL(path)
  File "ctypes\__init__.py", line 379, in __init__
OSError: [WinError 127] Die angegebene Prozedur wurde nicht gefunden
```

Last but not least, I tried BasicVSR++:
* `pip install -U openmim` 
ended with:
```
Collecting aliyun-python-sdk-core>=2.13.12 (from oss2~=2.17.0->openxlab->opendatalab->openmim)
  Using cached aliyun-python-sdk-core-2.15.1.tar.gz (443 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [7 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\Selur\AppData\Local\Temp\pip-install-v3fe2m_x\aliyun-python-sdk-core_efa56ca68579425b85b28aef6d602d71\setup.py", line 41, in <module>
          VERSION = __import__(PACKAGE).__version__
                    ^^^^^^^^^^^^^^^^^^^
      ModuleNotFoundError: No module named 'aliyunsdkcore'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

vsfemasr and vsrife: both seem to not know where to find the dlls, but not knowing what they are looking to I don't know what I should install or could install to my path.
vsrealesrgan: no clue how to fix it
basicvsr++: from what I see, the problem is with mmvc is not supporting Python 3.12 so far through precomiled files.

Got any hints/tips/… I could try to get vsfemasr, vsrife, vsrealesrgan and basicvsr++ working?

**Comment by HolyWu** [comment]
Why did you `pip install --pre torch-tensorrt --index-url https://download.pytorch.org/whl/nightly/cu121` after `pip install torch_tensorrt-2.4.0.dev0+8915f846d-cp312-cp312-win_amd64.whl`? The README didn't tell you to do that!

**Comment by Selur** [comment]
iirc I installed that since something was missing.
Will try again and report back.

**Comment by Selur** [comment]
Motivated that I got vs-dpir working with your help, I wanted to add your other projects, but can into a few problems.
(Sorry, this is a bit longer, but I wanted to be sure you know what I did so you might be able to see what I missed or did wrong.)

What I did was
* create 'Vapoursynth'-folder
* downloaded 'Windows embeddable package (64-bit)' from https://www.python.org/downloads/release/python-3123/
* extracted it into the 'Vapoursynth'-folder
* downloaded 'VapourSynth64-Portable-R68' from https://github.com/vapoursynth/vapoursynth/releases
* extracted it into the 'Vapoursynth'-folder
* download get-pip.py from https://bootstrap.pypa.io/get-pip.py into the 'Vapoursynth'-folder
* ran `python get-pip.py`
* adjusted `python312._pth` by adding:
  ```
  Scripts
  Lib\site-packages
  ```
* called `python -m pip install wheel/VapourSynth-68-cp312-cp312-win_amd64.whl`
* downloaded https://github.com/HolyWu/vs-dpir/releases/download/v4.0.0/torch_tensorrt-2.4.0.dev0+8915f846d-cp312-cp312-win_amd64.whl
* called`python -m pip install torch_tensorrt-2.4.0.dev0+8915f846d-cp312-cp312-win_amd64.whl`
* installed vs-dpir, by calling
  * `python -m pip install wheel`
  * `python -m pip install git+https://github.com/Jaded-Encoding-Thaumaturgy/vs-tools.git`
  * `python -m pip install -U vsdpir`
  * `python -m vsdpir`
* installed vsgan by calling:
  * `python -m pip install -U VSGAN`
* installed gsmfss:
  * `python -m pip install -U vsgmfss-fortuna`
* installed SwinIR by calling:
  * `python -m pip install -U vsswinir`
  * `python -m vsswinir`
* installed HINet by calling:
  * `python -m pip install --upgrade vshinet`
  * `python -m vshinet`
* installed AnimeSR by calling:
  * `python -m pip install -U vsanimesr`
* installed SCUNet by calling:
  * `python -m pip install -U vsscunet`
  * `python -m vsscunet`
* installed CodeFormer by calling:
  * `python -m pip install -U vscodeformer`
  * `python -m vscodeformer`
* installed GRLIR, by calling:
  * `python -m pip install antlr4-python3-runtime`
  * `python -m pip install -U vsgrlir`
  * `python -m vsgrlir`

So far so good.

Then I tried 'vsrealesrgan':
* `python -m pip install -U vsrealesrgan`
* `python -m vsrealesrgan`
this ended with:
```
Traceback (most recent call last):
  File "<frozen runpy>", line 189, in _run_module_as_main
  File "<frozen runpy>", line 148, in _get_module_details
  File "<frozen runpy>", line 112, in _get_module_details
  File "F:\Vapoursynth\Lib\site-packages\vsrealesrgan\__init__.py", line 9, in <module>
    import tensorrt
  File "F:\Vapoursynth\Lib\site-packages\tensorrt\__init__.py", line 18, in <module>
    from tensorrt_bindings import  *
ModuleNotFoundError: No module named 'tensorrt_bindings'
```
(I uninstalled vsrealesrgan then)

Then I tried 'vsrife':
* `python -m pip install --upgrade vsrife`
* `python -m vsrife`
this ended with:
```
Traceback (most recent call last):
  File "<frozen runpy>", line 189, in _run_module_as_main
  File "<frozen runpy>", line 148, in _get_module_details
  File "<frozen runpy>", line 112, in _get_module_details
  File "F:\Vapoursynth\Lib\site-packages\vsrife\__init__.py", line 9, in <module>
    import tensorrt
  File "F:\Vapoursynth\Lib\site-packages\tensorrt\__init__.py", line 18, in <module>
    from tensorrt_bindings import  *
```
(I uninstalled vsrife then)

Then I tried 'vsfemasr':
* `python -m pip install -U vsfemasr` 
* `python -m vsfemasr`
endend with:
```
Traceback (most recent call last):
  File "<frozen runpy>", line 189, in _run_module_as_main
  File "<frozen runpy>", line 148, in _get_module_details
  File "<frozen runpy>", line 112, in _get_module_details
  File "F:\Vapoursynth\Lib\site-packages\vsfemasr\__init__.py", line 8, in <module>
    import tensorrt
  File "F:\Vapoursynth\Lib\site-packages\tensorrt\__init__.py", line 18, in <module>
    from tensorrt_bindings import  *
ModuleNotFoundError: No module named 'tensorrt_bindings'
```

Last I tried BasicVSR++:
* `python -m pip install -U openmim` 
ended with:
```
Collecting aliyun-python-sdk-core>=2.13.12 (from oss2~=2.17.0->openxlab->opendatalab->openmim)
  Using cached aliyun-python-sdk-core-2.15.1.tar.gz (443 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [7 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\Selur\AppData\Local\Temp\pip-install-q56iod47\aliyun-python-sdk-core_8dd359ccd9be4d9f9b5ed369a6b219b3\setup.py", line 41, in <module>
          VERSION = __import__(PACKAGE).__version__
                    ^^^^^^^^^^^^^^^^^^^
      ModuleNotFoundError: No module named 'aliyunsdkcore'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

=> not using  "--pre torch-tensorrt" changed the output.

**Comment by HolyWu** [comment]
Your `tensorrt` python package was not properly installed. Normally installing tensorrt 10 from PyPI will also install `tensorrt-cu12_bindings` and `tensorrt-cu12_libs` automatically. I have updated the README to specifically install them as well.

Besides, some other projects (vs-femasr, vs-gmfss_fortuna, vs-realesrgan) depend on `torch_tensorrt_fx_only` package. That package is outdated and uses the same directory name as `torch_tensorrt` package. Hence, some files could get overwritten by old files if you installed the aforementioned projects after `torch_tensorrt` package had been installed.

**Comment by Selur** [comment]
!Thanks!, using:
* `python -m pip install torch_tensorrt_fx_only`
* `python -m pip install wheel`
* `python -m pip install tensorrt==10.0.1 tensorrt-cu12_bindings==10.0.1 tensorrt-cu12_libs==10.0.1 --extra-index-url https://pypi.nvidia.com`
seems to do the trick 👍 
(only thing that doesn't work atm. is BasicVSR++)

btw.
* `python -m pip install -U vsdpir`
only installed v4.0.0, will try in a few days again, whether it then updates to 4.1.0.

**Comment by HolyWu** [comment]
Huh? It's already on [PyPI](https://pypi.org/project/vsdpir/#history) a few hours ago.

**Comment by Selur** [comment]
Strange, just triggered it again:
```
F:\Vapoursynth>python -m pip install -U vsdpir
Requirement already satisfied: vsdpir in f:\vapoursynth\lib\site-packages (4.0.0)
Collecting vsdpir
  Using cached vsdpir-4.1.0-py3-none-any.whl.metadata (1.8 kB)
Requirement already satisfied: numpy in f:\vapoursynth\lib\site-packages (from vsdpir) (1.26.4)
Requirement already satisfied: requests in f:\vapoursynth\lib\site-packages (from vsdpir) (2.31.0)
INFO: pip is looking at multiple versions of vsdpir to determine which version is compatible with other requirements. This could take a while.
Requirement already satisfied: torch>=2.3.0 in f:\vapoursynth\lib\site-packages (from vsdpir) (2.3.0)
Requirement already satisfied: tqdm in f:\vapoursynth\lib\site-packages (from vsdpir) (4.66.4)
Requirement already satisfied: vapoursynth>=66 in f:\vapoursynth\lib\site-packages (from vsdpir) (68)
Requirement already satisfied: vstools in f:\vapoursynth\lib\site-packages (from vsdpir) (3.1.0)
Requirement already satisfied: filelock in f:\vapoursynth\lib\site-packages (from torch>=2.3.0->vsdpir) (3.14.0)
Requirement already satisfied: typing-extensions>=4.8.0 in f:\vapoursynth\lib\site-packages (from torch>=2.3.0->vsdpir) (4.11.0)
Requirement already satisfied: sympy in f:\vapoursynth\lib\site-packages (from torch>=2.3.0->vsdpir) (1.12)
Requirement already satisfied: networkx in f:\vapoursynth\lib\site-packages (from torch>=2.3.0->vsdpir) (3.3)
Requirement already satisfied: jinja2 in f:\vapoursynth\lib\site-packages (from torch>=2.3.0->vsdpir) (3.1.4)
Requirement already satisfied: fsspec in f:\vapoursynth\lib\site-packages (from torch>=2.3.0->vsdpir) (2024.5.0)
Requirement already satisfied: mkl<=2021.4.0,>=2021.1.1 in f:\vapoursynth\lib\site-packages (from torch>=2.3.0->vsdpir) (2021.4.0)
Requirement already satisfied: charset-normalizer<4,>=2 in f:\vapoursynth\lib\site-packages (from requests->vsdpir) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in f:\vapoursynth\lib\site-packages (from requests->vsdpir) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in f:\vapoursynth\lib\site-packages (from requests->vsdpir) (2.2.1)
Requirement already satisfied: certifi>=2017.4.17 in f:\vapoursynth\lib\site-packages (from requests->vsdpir) (2024.2.2)
Requirement already satisfied: colorama in f:\vapoursynth\lib\site-packages (from tqdm->vsdpir) (0.4.6)
Requirement already satisfied: stgpytools>=1.0.5 in f:\vapoursynth\lib\site-packages (from vstools->vsdpir) (1.0.5)
Requirement already satisfied: rich>=12.6.0 in f:\vapoursynth\lib\site-packages (from vstools->vsdpir) (13.7.1)
Requirement already satisfied: intel-openmp==2021.* in f:\vapoursynth\lib\site-packages (from mkl<=2021.4.0,>=2021.1.1->torch>=2.3.0->vsdpir) (2021.4.0)
Requirement already satisfied: tbb==2021.* in f:\vapoursynth\lib\site-packages (from mkl<=2021.4.0,>=2021.1.1->torch>=2.3.0->vsdpir) (2021.12.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in f:\vapoursynth\lib\site-packages (from rich>=12.6.0->vstools->vsdpir) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in f:\vapoursynth\lib\site-packages (from rich>=12.6.0->vstools->vsdpir) (2.18.0)
Requirement already satisfied: MarkupSafe>=2.0 in f:\vapoursynth\lib\site-packages (from jinja2->torch>=2.3.0->vsdpir) (2.1.5)
Requirement already satisfied: mpmath>=0.19 in f:\vapoursynth\lib\site-packages (from sympy->torch>=2.3.0->vsdpir) (1.3.0)
Requirement already satisfied: mdurl~=0.1 in f:\vapoursynth\lib\site-packages (from markdown-it-py>=2.2.0->rich>=12.6.0->vstools->vsdpir) (0.1.2)
```
Even running `python -m pip cache purge` before `python -m pip install -U vsdpir` doesn't change it.

Okay, when I call `python -m pip install -U vsdpir==4.1.0`
```
Collecting vsdpir==4.1.0
  Using cached vsdpir-4.1.0-py3-none-any.whl.metadata (1.8 kB)
Requirement already satisfied: numpy in f:\vapoursynth\lib\site-packages (from vsdpir==4.1.0) (1.26.4)
Requirement already satisfied: requests in f:\vapoursynth\lib\site-packages (from vsdpir==4.1.0) (2.31.0)
INFO: pip is looking at multiple versions of vsdpir to determine which version is compatible with other requirements. This could take a while.
ERROR: Could not find a version that satisfies the requirement torch>=2.4.0.dev (from vsdpir) (from versions: 2.2.0, 2.2.1, 2.2.2, 2.3.0)
ERROR: No matching distribution found for torch>=2.4.0.dev
```

**Comment by HolyWu** [comment]
The release note has mentioned PyTorch version bump. You need to install nightly build.

**Comment by Selur** [comment]
Ah, I still need
`python -m pip install torch_tensorrt-2.4.0.dev20240518+cu121-cp312-cp312-win_amd64.whl`
I wrongly assumed that:
`python -m pip install --pre torch-tensorrt --index-url https://download.pytorch.org/whl/nightly/cu121`
would already do the job.
=> got 4.1.0 now thanks!

**Comment by Selur** [comment]
Argh,.. I still didn't get it properly. Tried it anew to be sure I got the right order, but with:

* created 'Vapoursynth'-folder
* downloaded 'Windows embeddable package (64-bit)' from https://www.python.org/downloads/release/python-3123/
* extracted it into the 'Vapoursynth'-folder
* downloaded 'VapourSynth64-Portable-R68' from https://github.com/vapoursynth/vapoursynth/releases
* extracted it into the 'Vapoursynth'-folder
* finished Vapoursynth portable installation:
  * adjusted `python312._pth` by adding:
  ```
  Scripts
  Lib\site-packages
  ```
  * installed pip:
    * download get-pip.py from https://bootstrap.pypa.io/get-pip.py into the 'Vapoursynth'-folder
    * `python get-pip.py`
  * `python -m pip install wheel\VapourSynth-68-cp312-cp312-win_amd64.whl`
* installed torch dependencies:
  * `python -m pip install wheel`
  * installed TensorRT FX
    * `python -m pip install torch_tensorrt_fx_only`
  * installed Pytorch 2.4 dev  (uninstalled torch 2.3.0 and installed Pytorch 2.4.0.dev20240519+cu121)
    * `python -m pip install --pre torch torchvision --index-url https://download.pytorch.org/whl/nightly/cu121`
  * installed TensorRT
   * `python -m pip install https://github.com/HolyWu/vs-dpir/releases/download/v4.1.0/torch_tensorrt-2.4.0.dev20240518+cu121-cp312-cp312-win_amd64.whl`
   * `python -m pip install tensorrt==10.0.1 tensorrt-cu12_bindings==10.0.1 tensorrt-cu12_libs==10.0.1 --extra-index-url https://pypi.nvidia.com`
it fails with vsfemasr. :(
calling `python -m pip install -U vsfemasr` 
I get:
```
INFO: pip is looking at multiple versions of torch-tensorrt-fx-only to determine which version is compatible with other requirements. This could take a while.
Collecting torch-tensorrt-fx-only>=1.3.0 (from vsfemasr)
  Using cached torch_tensorrt_fx_only-1.3.0-py3-none-any.whl.metadata (13 kB)
Collecting vsfemasr
  Using cached vsfemasr-1.1.0-py3-none-any.whl.metadata (9.9 kB)
  Using cached vsfemasr-1.0.0-py3-none-any.whl.metadata (9.9 kB)
ERROR: Cannot install vsfemasr and vsfemasr==1.0.0 because these package versions have conflicting dependencies.

The conflict is caused by:
    vsfemasr 1.0.0 depends on torch>=1.13.0
    torch-tensorrt-fx-only 1.4.0.post1 depends on torch<2.2 and >=2.0.1
    vsfemasr 1.0.0 depends on torch>=1.13.0
    torch-tensorrt-fx-only 1.3.0 depends on torch<1.14.0 and >=1.13.0

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict
```
calling `python -m pip install -U vsfemasr==1.2.0`, I get:
```
INFO: pip is looking at multiple versions of torch-tensorrt-fx-only to determine which version is compatible with other requirements. This could take a while.
Collecting torch-tensorrt-fx-only>=1.3.0 (from vsfemasr==1.2.0)
  Using cached torch_tensorrt_fx_only-1.3.0-py3-none-any.whl.metadata (13 kB)
ERROR: Cannot install vsfemasr and vsfemasr==1.2.0 because these package versions have conflicting dependencies.

The conflict is caused by:
    vsfemasr 1.2.0 depends on torch>=1.13.0
    torch-tensorrt-fx-only 1.4.0.post1 depends on torch<2.2 and >=2.0.1
    vsfemasr 1.2.0 depends on torch>=1.13.0
    torch-tensorrt-fx-only 1.3.0 depends on torch<1.14.0 and >=1.13.0

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
```

=> What is the right order to install the torch dependencies?

**Comment by HolyWu** [comment]
Either don't install projects which depend on outdated `torch_tensorrt_fx_only` at the moment, or install them with `--no-deps` flag and hope they don't break.

**Comment by Selur** [comment]
resetting everything up again, seems to work, will do some testing which tools installation breaks the rest.

**Comment by Selur** [comment]
Okay, not using:
* vsfemasr
* vsanimesr
* vsrealesrgan
* vsgmfss-fortuna
keeps vs-dpir and vs-rife working.
=> So sticking with R65 and the older vs-dpir and vs-rife versions, seems to be the best for me. Looking forward to any update on some of your filters.

**Comment by Selur** [comment]
Small update:
* vsfemasr 2.0.0 works fine.
* got BasicVSR++ working with [site-packages_mmcv_p312_cuda121.zip](https://forum.selur.net/attachment.php?aid=2531) provided by Dan64. (ugly since it's not a wheel, but it works ;))

so atm. only:
* vsanimesr
* vsrealesrgan
* vsgmfss-fortuna
are not usable with R68 without breaking vs-dpir and vs-rife.
