### ISSUE TITLE
Use gray models when passing a GRAY clip

### ISSUE THREAD

**Issue by LightArrowsEXE** [HolyWu/vs-dpir#9]
I realised there's gray models included with the original DPIR. Is there a reason those can't be used when passing a GRAY clip converted to RGBS (or if it's possible, just pure GRAY support)?

**Comment by HolyWu** [comment]
It seems that deblocking_grayscale model is quite ineffective compared to deblocking_color model, no matter the input's resolution is mod-8 or not.
